---
##############
#   INFRA    #
##############
- name: DEPROVISION VMS
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Deprovision all VM instances
      shell: |
        cloud_instance delete -d {{ deployment_id }}
