---
##############
#   INFRA    #
##############
- name: GATHER DEPLOYMENT INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tags:
    - infra
    - cloud_instance
  tasks:
    - name: Gather current deployment instances
      shell: |
        cloud_instance gather -d {{ deployment_id }}
      register: instances

    - name: Build ansible inventory dynamically
      add_host:
        # id
        name: "{{ item.public_ip }}"
        id: "{{ item.id }}"

        # locality
        cloud: "{{ item.cloud }}"
        region: "{{ item.region }}"
        zone: "{{ item.zone }}"

        # addresses
        public_hostname: "{{ item.public_hostname }}"
        public_ip: "{{ item.public_ip }}"
        private_hostname: "{{ item.private_hostname }}"
        private_ip: "{{ item.private_ip }}"

        # tags
        ansible_user: "{{ item.ansible_user }}"
        ansible_host: "{{ item.public_ip }}"
        groups: "{{ item.inventory_groups }}"
        cluster_name: "{{ item.cluster_name }}"
        group_name: "{{ item.group_name }}"
        extra_vars: "{{ item.extra_vars }}"
        
      loop: "{{ instances.stdout | from_json }}"

- name: UPGRADE COCKROACHDB BINARY
  hosts: cockroachdb
  gather_facts: yes
  become: yes
  vars:
    # cockroachdb_version: v23.2.17
    # iknowwhatiamdoing: no
    cockroachdb_autofinalize: yes
    cockroachdb_advertise_addr: "{{ public_ip }}"
    cockroachdb_repo_url: https://binaries.cockroachdb.com
  tasks:
    - name: get current cockroachdb version
      shell: |
        cockroach version | head -n1 | awk '{print $3}'
      register: out

    - name: preserve downgrade
      run_once: yes
      shell: |
        cockroach sql \
          --certs-dir=/var/lib/cockroach/certs \
          --host={{ cockroachdb_advertise_addr }} \
          -e "SET CLUSTER SETTING cluster.preserve_downgrade_option = '{{ out.stdout[1:5] }}';"
      when: not cockroachdb_autofinalize

    - name: Create the binary-type map
      set_fact:
        # map the machine CPU type to the matching filename component
        bin_arch:
          aarch64: arm64
          x86_64: amd64

    - name: Check that the CockroachDB tarball exists locally
      stat:
        path: cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz
      register: out

    - name: Download CockroachDB binary
      shell: |
        wget -q {{ cockroachdb_repo_url }}/cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz
      when: not out.stat.exists
    
    - name: Install CockroachDB binary
      shell: |
        tar xvf cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz
        mv cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}/cockroach /usr/local/bin/cockroach
        chmod 755 /usr/local/bin/cockroach
        mkdir -p /usr/local/lib/cockroach/
        mv cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}/lib/libgeos*.so /usr/local/lib/cockroach/
        rm -rf cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}
  

- name: RESTART COCKROACHDB
  hosts: cockroachdb
  gather_facts: no
  serial: 1
  become: yes
  vars:
    cockroachdb_upgrade_delay: 30
  tasks:
    - name: Ensure cockroachdb service is restarted
      shell: |
        systemctl restart cockroachdb

    - name: Wait until the node has rejoined the cluster
      shell: |
        # TODO
        sleep 5
        
    - name: Pause between upgrades
      pause:
        seconds: "{{ cockroachdb_upgrade_delay }}"


- name: WAIT FOR UPGRADE FINALIZATION
  hosts: cockroachdb
  gather_facts: no
  run_once: yes
  become: yes
  vars:
    cockroachdb_autofinalize: yes
  tasks:
    - name: Wait until the upgrade finalizes
      shell: |
        # TODO
        sleep 5
      when: cockroachdb_autofinalize
