INSERT INTO public.settings (
    key,
    default_value,
    value_type,
    category,
    is_secret,
    description
) VALUES
    ('s3_url', '', 'url', 'storage', false, 'Base S3 endpoint used for tenant external connections.'),
    ('s3_admin_url', '', 'url', 'storage', false, 'Optional admin endpoint for the S3-compatible provider if different from s3_url.'),
    ('s3_admin_access_key', '', 'string', 'storage', true, 'Administrative access key used by the control plane to provision buckets and tenant credentials.'),
    ('s3_admin_secret_key', '', 'string', 'storage', true, 'Administrative secret key used by the control plane to provision buckets and tenant credentials.'),
    ('s3_default_retention_days', '', 'integer', 'storage', false, 'Default lifecycle retention applied to tenant backup buckets in days.'),
    ('default_password', '', 'string', 'cluster_defaults', true, 'Default password used by legacy provisioning flows.'),
    ('default_username', '', 'string', 'cluster_defaults', false, 'Default administrative username created in tenant clusters.'),
    ('licence_key', '', 'string', 'licensing', true, 'CockroachDB enterprise license key used during provisioning.'),
    ('licence_org', '', 'string', 'licensing', false, 'CockroachDB enterprise license organization used during provisioning.'),
    ('playbooks_url', '', 'url', 'playbooks', false, 'Source URL for external playbook synchronization.'),
    ('playbooks_url_cache_expiry', '', 'integer', 'playbooks', false, 'Playbook source cache expiry in seconds.'),
    ('prom_url', '', 'url', 'observability', false, 'Prometheus base URL used for dashboard and health queries.'),
    ('sso_auth_url', '', 'url', 'sso', false, 'Legacy SSO authorization endpoint URL.'),
    ('sso_cache_expiry', '', 'integer', 'sso', false, 'Legacy SSO cache expiry in seconds.'),
    ('sso_claim_name', '', 'string', 'sso', false, 'Legacy SSO claim used to identify the signed-in principal.'),
    ('sso_client_id', '', 'string', 'sso', false, 'Legacy SSO client identifier.'),
    ('sso_client_secret', '', 'string', 'sso', true, 'Legacy SSO client secret.'),
    ('sso_issuer', '', 'url', 'sso', false, 'Legacy SSO issuer URL.'),
    ('sso_jwks_url', '', 'url', 'sso', false, 'Legacy SSO JWKS endpoint URL.'),
    ('sso_redirect_uri', '', 'url', 'sso', false, 'Legacy SSO redirect URI.'),
    ('sso_token_url', '', 'url', 'sso', false, 'Legacy SSO token endpoint URL.'),
    ('sso_userinfo_url', '', 'url', 'sso', false, 'Legacy SSO userinfo endpoint URL.'),
    ('cp_enterprise_license_key', '', 'string', 'oidc', true, 'Reserved enterprise control-plane license key setting.'),
    ('oidc_enabled', 'false', 'boolean', 'oidc', false, 'Enable OIDC authentication for the control plane.'),
    ('oidc_issuer_url', '', 'url', 'oidc', false, 'OIDC issuer URL.'),
    ('oidc_client_id', '', 'string', 'oidc', false, 'OIDC client identifier.'),
    ('oidc_client_secret', '', 'string', 'oidc', true, 'OIDC client secret.'),
    ('oidc_scopes', 'openid profile email', 'string', 'oidc', false, 'Space-delimited OIDC scopes requested during login.'),
    ('oidc_audience', '', 'string', 'oidc', false, 'Expected OIDC audience when audience verification is enabled.'),
    ('oidc_extra_auth_params', '{}', 'json', 'oidc', false, 'JSON object of additional OIDC authorization request parameters.'),
    ('oidc_redirect_uri', '', 'url', 'oidc', false, 'OIDC redirect URI handled by the control plane.'),
    ('oidc_login_path', '/auth/login', 'path', 'oidc', false, 'Application path used to initiate OIDC login.'),
    ('oidc_session_cookie_name', 'cp_session', 'string', 'oidc', false, 'Cookie name used for the encrypted OIDC session.'),
    ('oidc_state_cookie_name', 'cp_oidc_state', 'string', 'oidc', false, 'Cookie name used for OIDC state validation.'),
    ('oidc_nonce_cookie_name', 'cp_oidc_nonce', 'string', 'oidc', false, 'Cookie name used for OIDC nonce validation.'),
    ('oidc_next_cookie_name', 'cp_oidc_next', 'string', 'oidc', false, 'Cookie name used to preserve the post-login redirect target.'),
    ('oidc_cookie_secure', 'true', 'boolean', 'oidc', false, 'Whether OIDC cookies should be marked Secure.'),
    ('oidc_cookie_samesite', 'lax', 'string', 'oidc', false, 'SameSite policy applied to OIDC cookies.'),
    ('oidc_cookie_domain', '', 'string', 'oidc', false, 'Optional domain attribute applied to OIDC cookies.'),
    ('oidc_verify_audience', 'true', 'boolean', 'oidc', false, 'Whether to verify the audience claim in OIDC tokens.'),
    ('oidc_ui_username_claim', 'email', 'string', 'oidc', false, 'OIDC claim displayed as the UI username.'),
    ('oidc_authz_readonly_groups', '', 'csv', 'oidc', false, 'Comma-delimited OIDC groups that map to the read-only control-plane role.'),
    ('oidc_authz_user_groups', '', 'csv', 'oidc', false, 'Comma-delimited OIDC groups that map to the standard user control-plane role.'),
    ('oidc_authz_admin_groups', '', 'csv', 'oidc', false, 'Comma-delimited OIDC groups that map to the admin control-plane role.'),
    ('oidc_authz_groups_claim', 'groups', 'string', 'oidc', false, 'OIDC claim that contains the user''s group memberships.');