"""Shared infrastructure entrypoints for DB lifecycle and FastAPI dependencies."""

from .db import close_db, get_pool, get_repo, initialize_postgres
from .dependencies import (
    get_admin_service,
    get_api_keys_service,
    get_auth_service,
    get_cluster_backups_service,
    get_cluster_jobs_service,
    get_cluster_service,
    get_cluster_users_service,
    get_dashboard_service,
    get_events_service,
    get_jobs_service,
    get_playbooks_service,
    get_regions_service,
    get_settings_service,
    get_versions_service,
)
from .util import (
    RequestIDFilter,
    ShorthandFormatter,
    as_bool,
    connect_cluster_db,
    decrypt_api_key_secret,
    decrypt_secret,
    encrypt_api_key_secret,
    encrypt_secret,
    request_id_ctx,
    safe_csv_set,
    safe_json_string_dict,
    safe_next_path,
    validate_api_key_crypto_config,
    validate_secret_crypto_config,
)

__all__ = [
    "close_db",
    "get_pool",
    "get_repo",
    "initialize_postgres",
    "get_admin_service",
    "get_auth_service",
    "get_cluster_backups_service",
    "get_cluster_jobs_service",
    "get_cluster_service",
    "get_cluster_users_service",
    "get_compute_unit_service",
    "get_dashboard_service",
    "get_events_service",
    "get_jobs_service",
    "get_playbooks_service",
    "get_regions_service",
    "get_settings_service",
    "get_versions_service",
    "get_api_keys_service",
    "RequestIDFilter",
    "ShorthandFormatter",
    "as_bool",
    "connect_cluster_db",
    "decrypt_secret",
    "decrypt_api_key_secret",
    "encrypt_secret",
    "encrypt_api_key_secret",
    "request_id_ctx",
    "safe_csv_set",
    "safe_json_string_dict",
    "safe_next_path",
    "validate_secret_crypto_config",
    "validate_api_key_crypto_config",
]
