#!/usr/bin/env python3
"""
docsync.py

Generate LLM-friendly project documentation from Python source.

Usage:
    python tools/docsync.py --write
    python tools/docsync.py --check
"""

from __future__ import annotations

import argparse
import ast
import hashlib
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
DOCS = ROOT / "docs"
GENERATED = DOCS / "generated"


@dataclass
class FunctionInfo:
    name: str
    lineno: int
    docstring: str | None


@dataclass
class ClassInfo:
    name: str
    lineno: int
    docstring: str | None


@dataclass
class ModuleInfo:
    path: Path
    module_name: str
    docstring: str | None
    classes: list[ClassInfo]
    functions: list[FunctionInfo]


def module_name_from_path(path: Path) -> str:
    rel = path.relative_to(SRC).with_suffix("")
    return ".".join(rel.parts)


def parse_python_file(path: Path) -> ModuleInfo:
    tree = ast.parse(path.read_text(encoding="utf-8"))

    classes: list[ClassInfo] = []
    functions: list[FunctionInfo] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes.append(
                ClassInfo(
                    name=node.name,
                    lineno=node.lineno,
                    docstring=ast.get_docstring(node),
                )
            )

        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            if not node.name.startswith("_"):
                functions.append(
                    FunctionInfo(
                        name=node.name,
                        lineno=node.lineno,
                        docstring=ast.get_docstring(node),
                    )
                )

    return ModuleInfo(
        path=path,
        module_name=module_name_from_path(path),
        docstring=ast.get_docstring(tree),
        classes=classes,
        functions=functions,
    )


def scan_project() -> list[ModuleInfo]:
    modules: list[ModuleInfo] = []

    for path in sorted(SRC.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue

        modules.append(parse_python_file(path))

    return modules


def first_sentence(text: str | None) -> str:
    if not text:
        return "_No docstring._"

    return text.strip().split("\n")[0]


def render_code_map(modules: list[ModuleInfo]) -> str:
    lines: list[str] = []

    lines.append("# Generated Code Map")
    lines.append("")
    lines.append("> Generated by `tools/docsync.py`. Do not edit manually.")
    lines.append("")

    current_package = None

    for module in modules:
        package = module.module_name.split(".")[0]

        if package != current_package:
            current_package = package
            lines.append(f"## `{package}`")
            lines.append("")

        rel_path = module.path.relative_to(ROOT)

        lines.append(f"### `{module.module_name}`")
        lines.append("")
        lines.append(f"Path: `{rel_path}`")
        lines.append("")
        lines.append(first_sentence(module.docstring))
        lines.append("")

        if module.classes:
            lines.append("Classes:")
            for cls in module.classes:
                lines.append(
                    f"- `{cls.name}` — line {cls.lineno}: "
                    f"{first_sentence(cls.docstring)}"
                )
            lines.append("")

        if module.functions:
            lines.append("Functions:")
            for fn in module.functions:
                lines.append(
                    f"- `{fn.name}()` — line {fn.lineno}: "
                    f"{first_sentence(fn.docstring)}"
                )
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def file_hash(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def write_or_check(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""

    if file_hash(existing) == file_hash(content):
        return True

    if check:
        print(f"STALE: {path.relative_to(ROOT)}")
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"WROTE: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not args.write and not args.check:
        parser.error("Use either --write or --check")

    modules = scan_project()
    code_map = render_code_map(modules)

    ok = write_or_check(
        GENERATED / "code-map.md",
        code_map,
        check=args.check,
    )

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
