---
- name: SCALE NODE CPUS
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tags:
    - infra
    - cloud_instance
  tasks:
    - name: resize disks
      shell: |
        cloud_instance resize \
          -d {{ deployment_id }} \
          --disk-size {{ disk_size }} \
          --pause-between 30 \
          --filter-by-groups cockroachdb
    
    - name: Gather VM details of current deployment
      shell: |
        cloud_instance gather -d {{ deployment_id }}
      register: instances

    - name: Build ansible inventory dynamically
      add_host:
        # id
        name: "{{ item.public_ip }}"
        id: "{{ item.id }}"

        # locality
        cloud: "{{ item.cloud }}"
        region: "{{ item.region }}"
        zone: "{{ item.zone }}"

        # addresses
        public_hostname: "{{ item.public_hostname }}"
        public_ip: "{{ item.public_ip }}"
        private_hostname: "{{ item.private_hostname }}"
        private_ip: "{{ item.private_ip }}"

        # tags
        ansible_user: "{{ item.ansible_user }}"
        ansible_host: "{{ item.public_ip }}"
        groups: "{{ item.inventory_groups }}"
        cluster_name: "{{ item.cluster_name }}"
        group_name: "{{ item.group_name }}"
        extra_vars: "{{ item.extra_vars }}"
      loop: "{{ instances.stdout | from_json }}"


- name: RESIZE FILESYSTEM ON COCKROACHDB NODES
  hosts: cockroachdb
  gather_facts: yes
  become: yes
  tags:
    - platform
    - cockroachdb
  tasks:
    - name: Find attached disks
      shell: |
        lsblk -o NAME,TYPE,SIZE -p -n -b -s | \
          awk '$NF ~ /[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/' | \
          grep -v '└─' | \
          grep disk | \
          awk '{print $1}'
      args:
        executable: /bin/bash
      register: _disks

    - name: Resize the filesystem
      when: _disks.stdout_lines | length > 0
      shell: |
        resize2fs {{ item }}
      loop: "{{ _disks.stdout_lines }}"

