---
- name: SCALE NODE CPUS
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tags:
    - infra
    - cloud_instance
  tasks:
    - name: modify instance type
      shell: |
        cloud_instance modify-instance-type \
          -d {{ deployment_id }} \
          --cpu-count {{ node_cpus }} \
          --pause-between 120 \
          --filter-by-groups cockroachdb \
          --defaults '{{ defaults | to_json }}'
      vars:
        defaults:
          aws:
            "2":
              default: t3.large # m6i.large
              "4": c5.large
              "8": m6i.large
              "16": r5.large
            "4":
              default: t3.xlarge #m6i.xlarge
              "8": c5.xlarge
              "16": m6i.xlarge
              "32": r5.xlarge
            "8":
              default: m6i.2xlarge
              "16": c5.2xlarge
              "32": m6i.2xlarge
              "64": r5.2xlarge
            "16":
              default: m6i.4xlarge
              "32": c5.4xlarge
              "64": m6i.4xlarge
              "128": r5.4xlarge
            "32":
              default: m6i.8xlarge
              "128": m6i.8xlarge
              "256": r5.8xlarge
          azure:
            "2":
              "4": Standard_F2s_v2
              "8": Standard_D2s_v3
              "16": Standard_E2s_v3
              default: Standard_D2s_v3
            "4":
              "8": Standard_F4s_v2
              "16": Standard_D4s_v3
              "32": Standard_E4s_v3
              default: Standard_D4s_v3
            "8":
              "16": Standard_F8s_v2
              "32": Standard_D8s_v3
              "64": Standard_E8s_v3
              default: Standard_D8s_v3
            "16":
              "32": Standard_F16s_v2
              "64": Standard_D16s_v3
              "128": Standard_E16s_v3
              default: Standard_D16s_v3
            "32":
              "64": Standard_F32s_v2
              "128": Standard_D32s_v3
              "256": Standard_E32s_v3
              default: Standard_D32s_v3
          gcp:
            "2":
              default: e2-medium #n2-standard-2
              "4": n2-standard-2
              "8": n2-standard-2
              "16": n2-highmem-2
            "4":
              default: e2-standard-4 #n2-standard-4
              "8": n2-standard-4
              "16": n2-standard-4
              "32": n2-highmem-4
            "8":
              default: e2-large #n2-standard-8
              "16": n2-standard-8
              "32": n2-standard-8
              "64": n2-highmem-8
            "16":
              default: n2-standard-16
              "32": n2-standard-16
              "64": n2-standard-16
              "128": n2-highmem-16
            "32":
              default: n2-standard-32
              "64": n2-standard-32
              "128": n2-standard-32
              "256": n2-highmem-32
